name: Build and Test feature branch

on:
  push:
    branches: [ "feature-DataFrame" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
      - name: Building with Maven
        run: mvn -B --quiet package

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
      - name: Testing
        run: mvn -B --quiet test