name: pipeline GithubCI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Building with Maven
        run: mvn compile
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: mvn test