name: pipeline GithubCI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    steps:
      - name: Building the project
      - run: mvn -B package --file pom.xml
  test: 
    steps:
      - needs: ["build"]
      - name: Testing
      - run: mvn test
