name: pipeline GithubCI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: mvn -B package --file pom.xml
  test:
    runs-on: ubuntu-latest
    steps:
      - needs: [build]
      - run: mvn test