name: Pipeline GithubCI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
      - name: Building with Maven
        run: mvn -B --quiet package
      - name: Build Docker
        run: docker build . -f Dockerfile.build -t atlantic0/build:latest
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PWD }}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
      - name: Push Docker image
        run: docker push atlantic0/build:latest

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
      - name: Testing
        run: mvn -B --quiet test
  
  deploy:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Repo checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PWD }}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
      - name: Build Docker image
        run: docker build -t atlantic0/devops_project:latest .
      - name: Push Docker image
        run: docker push atlantic0/devops_project:latest

      